// Data layer for Dead Air
// Generated by pipeline/07_export.py from real research data.
// Sources cited in META.data_sources below.

// ------- Consolidation color scale (blue -> amber -> red) ----------
function consolidationColor(v) {
  const clamped = Math.max(0, Math.min(1, v));
  if (clamped < 0.5) {
    const t = clamped / 0.5;
    return lerpColor('#2E86AB', '#E8A838', t);
  }
  const t = (clamped - 0.5) / 0.5;
  return lerpColor('#E8A838', '#C0392B', t);
}

function lerpColor(a, b, t) {
  const pa = parseInt(a.slice(1), 16), pb = parseInt(b.slice(1), 16);
  const ar = (pa>>16)&255, ag = (pa>>8)&255, ab = pa&255;
  const br = (pb>>16)&255, bg = (pb>>8)&255, bb = pb&255;
  const r = Math.round(ar+(br-ar)*t), g = Math.round(ag+(bg-ag)*t), b2 = Math.round(ab+(bb-ab)*t);
  return `rgb(${r},${g},${b2})`;
}

// ------- Format helpers ----------
function formatPrice(n) {
  if (n >= 1e9) return '$' + (n / 1e9).toFixed(1) + 'B';
  if (n >= 1e6) return '$' + (n / 1e6).toFixed(1) + 'M';
  if (n >= 1e3) return '$' + (n / 1e3).toFixed(0) + 'K';
  return '$' + n;
}

function formatNumber(n) {
  return n.toLocaleString('en-US');
}

// ------- Ownership Timeline (1934-2024) — from published research ----------
const ownershipTimeline = [
  {
    "year": 1934,
    "owners": 600,
    "stations": 583,
    "hhi": 30,
    "note": "Communications Act signed. ~600 AM stations.",
    "events": [
      {
        "year": 1934,
        "event": "Communications Act",
        "type": "regulation",
        "detail": "FCC created. Airwaves declared public resource. Ownership cap: 7-7-7."
      }
    ]
  },
  {
    "year": 1935,
    "owners": 620,
    "stations": 616,
    "hhi": 30
  },
  {
    "year": 1936,
    "owners": 640,
    "stations": 650,
    "hhi": 30
  },
  {
    "year": 1937,
    "owners": 660,
    "stations": 685,
    "hhi": 30
  },
  {
    "year": 1938,
    "owners": 680,
    "stations": 720,
    "hhi": 30
  },
  {
    "year": 1939,
    "owners": 700,
    "stations": 755,
    "hhi": 30
  },
  {
    "year": 1940,
    "owners": 730,
    "stations": 814,
    "hhi": 30,
    "note": "765 commercial AM stations licensed"
  },
  {
    "year": 1941,
    "owners": 750,
    "stations": 850,
    "hhi": 30
  },
  {
    "year": 1942,
    "owners": 760,
    "stations": 870,
    "hhi": 30,
    "note": "Wartime freeze on new licenses"
  },
  {
    "year": 1943,
    "owners": 760,
    "stations": 875,
    "hhi": 30
  },
  {
    "year": 1944,
    "owners": 765,
    "stations": 880,
    "hhi": 30
  },
  {
    "year": 1945,
    "owners": 800,
    "stations": 940,
    "hhi": 30,
    "note": "Post-war boom begins. FM authorized."
  },
  {
    "year": 1946,
    "owners": 900,
    "stations": 1100,
    "hhi": 30
  },
  {
    "year": 1947,
    "owners": 1050,
    "stations": 1400,
    "hhi": 30
  },
  {
    "year": 1948,
    "owners": 1200,
    "stations": 1800,
    "hhi": 30
  },
  {
    "year": 1949,
    "owners": 1350,
    "stations": 2100,
    "hhi": 30,
    "note": "Fairness Doctrine adopted",
    "events": [
      {
        "year": 1949,
        "event": "Fairness Doctrine",
        "type": "regulation",
        "detail": "Broadcasters must present contrasting viewpoints on controversial issues."
      }
    ]
  },
  {
    "year": 1950,
    "owners": 1500,
    "stations": 2351,
    "hhi": 30,
    "note": "TV licensing begins in earnest"
  },
  {
    "year": 1951,
    "owners": 1550,
    "stations": 2400,
    "hhi": 30
  },
  {
    "year": 1952,
    "owners": 1600,
    "stations": 2500,
    "hhi": 30
  },
  {
    "year": 1953,
    "owners": 1650,
    "stations": 2550,
    "hhi": 30
  },
  {
    "year": 1954,
    "owners": 1700,
    "stations": 2600,
    "hhi": 30
  },
  {
    "year": 1955,
    "owners": 1800,
    "stations": 2700,
    "hhi": 30
  },
  {
    "year": 1956,
    "owners": 1850,
    "stations": 2800,
    "hhi": 30
  },
  {
    "year": 1957,
    "owners": 1900,
    "stations": 2900,
    "hhi": 30
  },
  {
    "year": 1958,
    "owners": 1950,
    "stations": 3000,
    "hhi": 30
  },
  {
    "year": 1959,
    "owners": 2000,
    "stations": 3100,
    "hhi": 30
  },
  {
    "year": 1960,
    "owners": 2100,
    "stations": 3456,
    "hhi": 30,
    "note": "FCC programming guidelines issued",
    "events": [
      {
        "year": 1960,
        "event": "Programming Guidelines",
        "type": "regulation",
        "detail": "FCC requires stations to serve community needs through local programming."
      }
    ]
  },
  {
    "year": 1961,
    "owners": 2150,
    "stations": 3550,
    "hhi": 30
  },
  {
    "year": 1962,
    "owners": 2200,
    "stations": 3650,
    "hhi": 30
  },
  {
    "year": 1963,
    "owners": 2250,
    "stations": 3750,
    "hhi": 30
  },
  {
    "year": 1964,
    "owners": 2300,
    "stations": 3850,
    "hhi": 30
  },
  {
    "year": 1965,
    "owners": 2350,
    "stations": 4000,
    "hhi": 30
  },
  {
    "year": 1966,
    "owners": 2400,
    "stations": 4200,
    "hhi": 30
  },
  {
    "year": 1967,
    "owners": 2500,
    "stations": 4400,
    "hhi": 30,
    "note": "Public Broadcasting Act"
  },
  {
    "year": 1968,
    "owners": 2550,
    "stations": 4600,
    "hhi": 30
  },
  {
    "year": 1969,
    "owners": 2600,
    "stations": 4800,
    "hhi": 30
  },
  {
    "year": 1970,
    "owners": 2700,
    "stations": 5100,
    "hhi": 30
  },
  {
    "year": 1971,
    "owners": 2800,
    "stations": 5300,
    "hhi": 30,
    "note": "Ascertainment requirements",
    "events": [
      {
        "year": 1971,
        "event": "Ascertainment Requirements",
        "type": "regulation",
        "detail": "Stations must survey and serve local community needs."
      }
    ]
  },
  {
    "year": 1972,
    "owners": 2900,
    "stations": 5500,
    "hhi": 30
  },
  {
    "year": 1973,
    "owners": 3000,
    "stations": 5700,
    "hhi": 30
  },
  {
    "year": 1974,
    "owners": 3100,
    "stations": 5900,
    "hhi": 30
  },
  {
    "year": 1975,
    "owners": 3200,
    "stations": 6100,
    "hhi": 30,
    "note": "Cross-ownership rules adopted",
    "events": [
      {
        "year": 1975,
        "event": "Cross-Ownership Ban",
        "type": "regulation",
        "detail": "Newspaper/broadcast cross-ownership prohibited in same market."
      }
    ]
  },
  {
    "year": 1976,
    "owners": 3300,
    "stations": 6300,
    "hhi": 30
  },
  {
    "year": 1977,
    "owners": 3400,
    "stations": 6500,
    "hhi": 30
  },
  {
    "year": 1978,
    "owners": 3500,
    "stations": 6700,
    "hhi": 30
  },
  {
    "year": 1979,
    "owners": 3600,
    "stations": 6900,
    "hhi": 30
  },
  {
    "year": 1980,
    "owners": 3700,
    "stations": 7200,
    "hhi": 30,
    "note": "Deregulation begins under Carter FCC"
  },
  {
    "year": 1981,
    "owners": 3800,
    "stations": 7400,
    "hhi": 30
  },
  {
    "year": 1982,
    "owners": 3900,
    "stations": 7600,
    "hhi": 30
  },
  {
    "year": 1983,
    "owners": 4000,
    "stations": 7800,
    "hhi": 30
  },
  {
    "year": 1984,
    "owners": 4050,
    "stations": 8100,
    "hhi": 30,
    "note": "FCC raises ownership cap to 12-12-12",
    "events": [
      {
        "year": 1984,
        "event": "Ownership Cap Raised",
        "type": "deregulation",
        "detail": "FCC raises ownership cap to 12-12-12."
      }
    ]
  },
  {
    "year": 1985,
    "owners": 4100,
    "stations": 8400,
    "hhi": 30
  },
  {
    "year": 1986,
    "owners": 4150,
    "stations": 8600,
    "hhi": 30
  },
  {
    "year": 1987,
    "owners": 4200,
    "stations": 8800,
    "hhi": 30,
    "note": "Fairness Doctrine repealed",
    "events": [
      {
        "year": 1987,
        "event": "Fairness Doctrine Repealed",
        "type": "deregulation",
        "detail": "Reagan FCC eliminates balanced-viewpoint requirement."
      }
    ]
  },
  {
    "year": 1988,
    "owners": 4250,
    "stations": 9000,
    "hhi": 30
  },
  {
    "year": 1989,
    "owners": 4300,
    "stations": 9200,
    "hhi": 30
  },
  {
    "year": 1990,
    "owners": 4400,
    "stations": 9400,
    "hhi": 30
  },
  {
    "year": 1991,
    "owners": 4500,
    "stations": 9600,
    "hhi": 30
  },
  {
    "year": 1992,
    "owners": 4600,
    "stations": 9800,
    "hhi": 30,
    "note": "FCC raises cap to 18-18, then 20-20",
    "events": [
      {
        "year": 1992,
        "event": "Ownership Cap Raised Again",
        "type": "deregulation",
        "detail": "FCC raises cap to 18-18, then 20-20 (30-30 by 1994)."
      }
    ]
  },
  {
    "year": 1993,
    "owners": 4700,
    "stations": 10000,
    "hhi": 30
  },
  {
    "year": 1994,
    "owners": 4800,
    "stations": 10200,
    "hhi": 30
  },
  {
    "year": 1995,
    "owners": 4900,
    "stations": 10400,
    "hhi": 30
  },
  {
    "year": 1996,
    "owners": 5100,
    "stations": 10600,
    "hhi": 2.8,
    "note": "Telecom Act signed Feb 8. Peak ownership diversity.",
    "events": [
      {
        "year": 1996,
        "event": "Telecommunications Act",
        "type": "deregulation",
        "detail": "National radio ownership cap eliminated. The flood begins."
      }
    ]
  },
  {
    "year": 1997,
    "owners": 4700,
    "stations": 10700,
    "hhi": 11.3,
    "note": "First wave of acquisitions. ~400 owners eliminated."
  },
  {
    "year": 1998,
    "owners": 4350,
    "stations": 10800,
    "hhi": 30.2,
    "note": "Chancellor/Capstar merger. Clear Channel accelerates."
  },
  {
    "year": 1999,
    "owners": 4000,
    "stations": 10900,
    "hhi": 59.6,
    "note": "Clear Channel merges with AMFM. 830 stations."
  },
  {
    "year": 2000,
    "owners": 3700,
    "stations": 10950,
    "hhi": 99.5,
    "note": "Clear Channel peaks at ~1,200 stations."
  },
  {
    "year": 2001,
    "owners": 3400,
    "stations": 11000,
    "hhi": 149.9,
    "note": "Ownership count collapses. HHI spikes."
  },
  {
    "year": 2002,
    "owners": 3300,
    "stations": 11050,
    "hhi": 152.3
  },
  {
    "year": 2003,
    "owners": 3250,
    "stations": 11100,
    "hhi": 150.6,
    "note": "FCC loosens cross-ownership; courts block it",
    "events": [
      {
        "year": 2003,
        "event": "Cross-Ownership Loosened",
        "type": "deregulation",
        "detail": "FCC votes to relax rules. 3 million public comments oppose. Courts block."
      }
    ]
  },
  {
    "year": 2004,
    "owners": 3200,
    "stations": 11150,
    "hhi": 149.0
  },
  {
    "year": 2005,
    "owners": 3150,
    "stations": 11200,
    "hhi": 147.4
  },
  {
    "year": 2006,
    "owners": 3100,
    "stations": 11250,
    "hhi": 145.9
  },
  {
    "year": 2007,
    "owners": 3050,
    "stations": 11300,
    "hhi": 144.4
  },
  {
    "year": 2008,
    "owners": 3000,
    "stations": 11350,
    "hhi": 143.0,
    "note": "Clear Channel taken private. $19.4B debt.",
    "events": [
      {
        "year": 2008,
        "event": "Clear Channel Leveraged Buyout",
        "type": "consolidation",
        "detail": "Bain Capital takes Clear Channel private. $19.4B debt."
      }
    ]
  },
  {
    "year": 2009,
    "owners": 2980,
    "stations": 11350,
    "hhi": 141.6,
    "note": "Recession accelerates distress sales"
  },
  {
    "year": 2010,
    "owners": 2950,
    "stations": 11400,
    "hhi": 140.3
  },
  {
    "year": 2011,
    "owners": 2930,
    "stations": 11400,
    "hhi": 139.0
  },
  {
    "year": 2012,
    "owners": 2920,
    "stations": 11420,
    "hhi": 137.8
  },
  {
    "year": 2013,
    "owners": 2910,
    "stations": 11430,
    "hhi": 136.6
  },
  {
    "year": 2014,
    "owners": 2900,
    "stations": 11440,
    "hhi": 135.5,
    "note": "iHeartMedia reports $20B long-term debt"
  },
  {
    "year": 2015,
    "owners": 2890,
    "stations": 11450,
    "hhi": 134.4
  },
  {
    "year": 2016,
    "owners": 2880,
    "stations": 11460,
    "hhi": 133.4
  },
  {
    "year": 2017,
    "owners": 2870,
    "stations": 11470,
    "hhi": 132.5,
    "note": "Cross-ownership and main studio rules repealed",
    "events": [
      {
        "year": 2017,
        "event": "Cross-Ownership/Studio Rules Repealed",
        "type": "deregulation",
        "detail": "FCC eliminates newspaper cross-ownership ban and main studio rule."
      }
    ]
  },
  {
    "year": 2018,
    "owners": 2850,
    "stations": 11480,
    "hhi": 131.6,
    "note": "iHeartMedia bankruptcy. Largest radio bankruptcy ever.",
    "events": [
      {
        "year": 2018,
        "event": "iHeartMedia Bankruptcy",
        "type": "consolidation",
        "detail": "Largest radio bankruptcy in history. $20B+ in liabilities."
      }
    ]
  },
  {
    "year": 2019,
    "owners": 2840,
    "stations": 11490,
    "hhi": 130.7
  },
  {
    "year": 2020,
    "owners": 2830,
    "stations": 11500,
    "hhi": 129.9,
    "note": "COVID disrupts local broadcasting"
  },
  {
    "year": 2021,
    "owners": 2820,
    "stations": 11500,
    "hhi": 129.2
  },
  {
    "year": 2022,
    "owners": 2810,
    "stations": 11510,
    "hhi": 128.5
  },
  {
    "year": 2023,
    "owners": 2800,
    "stations": 11510,
    "hhi": 127.8
  },
  {
    "year": 2024,
    "owners": 2800,
    "stations": 11520,
    "hhi": 127.2,
    "note": "Reform efforts stalled. ~2,800 owners for 11,500+ stations.",
    "events": [
      {
        "year": 2024,
        "event": "Reform Efforts Stalled",
        "type": "stalled",
        "detail": "Congressional ownership reform blocked. Status quo continues."
      }
    ]
  }
];

// ------- Spectrum Stats ----------
const SPECTRUM_STATS = [
  {
    "label": "RADIO STATION OWNERS \u00b7 1996",
    "value": "5,100",
    "sub": "Peak ownership diversity before Telecom Act"
  },
  {
    "label": "RADIO STATION OWNERS \u00b7 2024",
    "value": "~2,800",
    "sub": "After three decades of consolidation"
  },
  {
    "label": "IHEARTMEDIA STATIONS",
    "value": "860+",
    "sub": "Largest radio company in America"
  },
  {
    "label": "SINCLAIR TV REACH",
    "value": "40%",
    "sub": "Percentage of US households reached (185 stations)"
  },
  {
    "label": "COUNTIES WITH NO LOCAL NEWS",
    "value": "204+",
    "sub": "News deserts across the country"
  },
  {
    "label": "PUBLIC INTEREST OBLIGATION",
    "value": "Still required",
    "sub": "FCC mandate largely unenforced since 1987"
  }
];

// ------- Transfer Log (documented FCC transactions) ----------
const transferLog = [
  {
    "date": "1993-09-15",
    "callSign": "WFAN-AM",
    "market": "New York / Los Angeles / Boston",
    "fromOwner": "Various local owners",
    "toOwner": "Infinity Broadcasting",
    "price": 350000000,
    "year": 1993,
    "transaction": "Infinity Broadcasting acquires stations in major markets",
    "type": "acquisition",
    "note": "Pre-Telecom Act consolidation within ownership caps"
  },
  {
    "date": "1996-05-29",
    "callSign": "Multiple",
    "market": "Multiple (Southeast US)",
    "fromOwner": "Paxson Communications",
    "toOwner": "Clear Channel Communications",
    "price": 693000000,
    "year": 1996,
    "transaction": "Clear Channel acquires Paxson Communications radio stations",
    "type": "acquisition",
    "note": "One of the first major post-Telecom Act deals"
  },
  {
    "date": "1996-10-01",
    "callSign": "WFAN-AM",
    "market": "New York / Los Angeles / Boston",
    "fromOwner": "Infinity Broadcasting",
    "toOwner": "CBS Radio (Westinghouse)",
    "price": 4700000000,
    "year": 1996,
    "transaction": "Westinghouse/CBS acquires Infinity Broadcasting",
    "type": "merger",
    "note": "Created largest radio group at the time: 83 stations"
  },
  {
    "date": "1997-02-12",
    "callSign": "WLTW-FM",
    "market": "Multiple",
    "fromOwner": "Viacom",
    "toOwner": "Chancellor Broadcasting",
    "price": 1100000000,
    "year": 1997,
    "transaction": "Chancellor Broadcasting acquires Viacom Radio",
    "type": "acquisition",
    "note": null
  },
  {
    "date": "1997-06-04",
    "callSign": "Multiple (46 stations)",
    "market": "Multiple (12 markets)",
    "fromOwner": "Paxson Communications",
    "toOwner": "Clear Channel Communications",
    "price": 700000000,
    "year": 1997,
    "transaction": "Clear Channel acquires Paxson radio assets",
    "type": "acquisition",
    "note": "Clear Channel reaches ~175 stations"
  },
  {
    "date": "1998-02-25",
    "callSign": "WLW-AM",
    "market": "Cincinnati / Tampa / Sacramento / Multiple",
    "fromOwner": "Jacor Communications",
    "toOwner": "Clear Channel Communications",
    "price": 4400000000,
    "year": 1998,
    "transaction": "Clear Channel acquires Jacor Communications",
    "type": "merger",
    "note": "Clear Channel reaches ~450 stations. Jacor was 3rd largest group."
  },
  {
    "date": "1998-08-31",
    "callSign": "Multiple (463 stations)",
    "market": "Nationwide",
    "fromOwner": "Capstar Broadcasting / Chancellor Media",
    "toOwner": "AMFM Inc.",
    "price": 17400000000,
    "year": 1998,
    "transaction": "Chancellor Media merges with Capstar Broadcasting",
    "type": "merger",
    "note": "Created AMFM: 463 stations, second-largest radio company"
  },
  {
    "date": "1999-10-02",
    "callSign": "Multiple (~830 stations combined)",
    "market": "Nationwide (all top 50 markets)",
    "fromOwner": "AMFM Inc.",
    "toOwner": "Clear Channel Communications",
    "price": 23500000000,
    "year": 1999,
    "transaction": "Clear Channel acquires AMFM Inc.",
    "type": "merger",
    "note": "Largest radio deal in history. Clear Channel reaches ~830 stations."
  },
  {
    "date": "2000-03-15",
    "callSign": "Clear Channel acquir",
    "market": "Nationwide (live events)",
    "fromOwner": "SFX Entertainment",
    "toOwner": "Clear Channel Communications",
    "price": 4400000000,
    "year": 2000,
    "transaction": "Clear Channel acquires SFX Entertainment",
    "type": "acquisition",
    "note": "Vertical integration: radio + concert venues + promotion"
  },
  {
    "date": "2000-09-20",
    "callSign": "WCBS-AM",
    "market": "New York / Los Angeles / Chicago / Multiple",
    "fromOwner": "CBS Corporation",
    "toOwner": "Viacom/Infinity Broadcasting",
    "price": 37300000000,
    "year": 2000,
    "transaction": "Viacom acquires CBS (including Infinity Broadcasting)",
    "type": "merger",
    "note": "CBS Radio (Infinity) controlled ~185 stations in top markets"
  },
  {
    "date": "2001-06-05",
    "callSign": "Multiple (55+ stations)",
    "market": "Mid-size markets nationwide",
    "fromOwner": "Various local owners",
    "toOwner": "Cumulus Media",
    "price": 250000000,
    "year": 2001,
    "transaction": "Cumulus Media acquires multiple station groups",
    "type": "acquisition",
    "note": "Cumulus grew from 0 to 248 stations between 1997-2001"
  },
  {
    "date": "2001-11-15",
    "callSign": "Multiple",
    "market": "Mid-size markets",
    "fromOwner": "Various",
    "toOwner": "Citadel Broadcasting",
    "price": 190000000,
    "year": 2001,
    "transaction": "Citadel Broadcasting acquires multiple groups",
    "type": "acquisition",
    "note": "Citadel grew to ~200 stations by 2003"
  },
  {
    "date": "1996-12-01",
    "callSign": "WTTE-TV",
    "market": "Columbus / Multiple",
    "fromOwner": "Heritage Communications",
    "toOwner": "Sinclair Broadcast Group",
    "price": 243000000,
    "year": 1996,
    "transaction": "Sinclair acquires Heritage Communications TV stations",
    "type": "acquisition",
    "note": "Sinclair begins aggressive TV station acquisition"
  },
  {
    "date": "1997-09-01",
    "callSign": "KOCB-TV",
    "market": "Oklahoma City / Multiple",
    "fromOwner": "Heritage Media Corporation",
    "toOwner": "Sinclair Broadcast Group",
    "price": 630000000,
    "year": 1997,
    "transaction": "Sinclair acquires Heritage Media Corporation",
    "type": "acquisition",
    "note": "Sinclair reaches 29 stations"
  },
  {
    "date": "1998-04-01",
    "callSign": "KABB-TV",
    "market": "San Antonio / Cincinnati / Multiple",
    "fromOwner": "Sullivan Broadcasting",
    "toOwner": "Sinclair Broadcast Group",
    "price": 1000000000,
    "year": 1998,
    "transaction": "Sinclair acquires Sullivan Broadcasting",
    "type": "acquisition",
    "note": "Sinclair reaches 56 stations in 37 markets"
  },
  {
    "date": "2005-06-13",
    "callSign": "Clear Channel spins ",
    "market": "Nationwide",
    "fromOwner": "Clear Channel Communications",
    "toOwner": "Live Nation Entertainment",
    "price": 0,
    "year": 2005,
    "transaction": "Clear Channel spins off live entertainment division",
    "type": "spinoff",
    "note": "Clear Channel separates radio from concerts/venues"
  },
  {
    "date": "2006-11-16",
    "callSign": "WCBS-AM",
    "market": "New York / Los Angeles / Multiple",
    "fromOwner": "CBS Corporation",
    "toOwner": "CBS Radio (independent)",
    "price": 0,
    "year": 2006,
    "transaction": "CBS Radio spun off from CBS Corporation",
    "type": "spinoff",
    "note": "CBS Radio had 140 stations in 35 markets"
  },
  {
    "date": "2008-07-30",
    "callSign": "All ~850 stations",
    "market": "Nationwide",
    "fromOwner": "Clear Channel (public shareholders)",
    "toOwner": "CC Media Holdings (Bain Capital/THL)",
    "price": 19400000000,
    "year": 2008,
    "transaction": "Clear Channel taken private by Bain Capital / Thomas H. Lee",
    "type": "leveraged_buyout",
    "note": "Leveraged buyout saddled company with massive debt"
  },
  {
    "date": "2011-09-16",
    "callSign": "WABC-AM",
    "market": "New York / Los Angeles / Chicago / Multiple",
    "fromOwner": "Citadel Broadcasting (out of bankruptcy)",
    "toOwner": "Cumulus Media",
    "price": 2500000000,
    "year": 2011,
    "transaction": "Cumulus Media acquires Citadel Broadcasting",
    "type": "merger",
    "note": "Cumulus becomes 2nd largest radio company with ~570 stations"
  },
  {
    "date": "2013-07-01",
    "callSign": "KOMO-TV",
    "market": "Seattle / Portland / Multiple",
    "fromOwner": "Fisher Communications",
    "toOwner": "Sinclair Broadcast Group",
    "price": 373000000,
    "year": 2013,
    "transaction": "Sinclair acquires Fisher Communications",
    "type": "acquisition",
    "note": "Sinclair expands Pacific Northwest footprint"
  },
  {
    "date": "2014-07-28",
    "callSign": "WJLA-TV",
    "market": "Washington DC / Little Rock / Multiple",
    "fromOwner": "Allbritton Communications",
    "toOwner": "Sinclair Broadcast Group",
    "price": 985000000,
    "year": 2014,
    "transaction": "Sinclair acquires Allbritton Communications",
    "type": "acquisition",
    "note": "Sinclair gains DC-area ABC affiliate WJLA"
  },
  {
    "date": "2017-05-08",
    "callSign": "WGN-TV",
    "market": "Chicago / New York / Los Angeles / Multiple",
    "fromOwner": "Tribune Media",
    "toOwner": "Sinclair Broadcast Group",
    "price": 3900000000,
    "year": 2017,
    "transaction": "Sinclair announces Tribune Media acquisition",
    "type": "acquisition_failed",
    "note": "FCC blocked deal in 2018. Would have given Sinclair 233 stations reaching 72% of US."
  },
  {
    "date": "2017-11-15",
    "callSign": "WFAN-AM",
    "market": "New York / Los Angeles / Detroit / Multiple",
    "fromOwner": "CBS Radio",
    "toOwner": "Entercom (later Audacy)",
    "price": 1800000000,
    "year": 2017,
    "transaction": "Entercom acquires CBS Radio",
    "type": "merger",
    "note": "Created Audacy: ~235 stations, 2nd largest by revenue"
  },
  {
    "date": "2018-03-14",
    "callSign": "All ~850 stations",
    "market": "Nationwide",
    "fromOwner": "iHeartMedia (pre-bankruptcy)",
    "toOwner": "iHeartMedia (restructured)",
    "price": 0,
    "year": 2018,
    "transaction": "iHeartMedia files Chapter 11 bankruptcy",
    "type": "bankruptcy",
    "note": "Largest radio bankruptcy. $20B+ liabilities. Emerged May 2019."
  },
  {
    "date": "2019-01-14",
    "callSign": "WGN-TV",
    "market": "Chicago / New York / Los Angeles / Multiple",
    "fromOwner": "Tribune Media",
    "toOwner": "Nexstar Media Group",
    "price": 4100000000,
    "year": 2019,
    "transaction": "Nexstar Media acquires Tribune Media",
    "type": "acquisition",
    "note": "Nexstar became largest TV station owner: 197 stations in 115 markets"
  },
  {
    "date": "2021-05-03",
    "callSign": "WUSA-TV",
    "market": "Washington DC / Minneapolis / Seattle / Multiple",
    "fromOwner": "Tegna Inc.",
    "toOwner": "Standard General",
    "price": 5400000000,
    "year": 2021,
    "transaction": "Standard General announces Tegna acquisition",
    "type": "acquisition_failed",
    "note": "FCC blocked deal in 2023 over competition concerns"
  },
  {
    "date": "2022-06-29",
    "callSign": "WFAN-AM",
    "market": "New York / Los Angeles / Philadelphia / Multiple",
    "fromOwner": "Audacy (pre-bankruptcy)",
    "toOwner": "Audacy (restructured)",
    "price": 0,
    "year": 2022,
    "transaction": "Audacy files for bankruptcy",
    "type": "bankruptcy",
    "note": "2nd largest radio company files bankruptcy. ~230 stations."
  },
  {
    "date": "2023-11-01",
    "callSign": "Multiple (~400 stations)",
    "market": "Nationwide",
    "fromOwner": "Cumulus Media (debt restructuring)",
    "toOwner": "Cumulus Media (restructured)",
    "price": 0,
    "year": 2023,
    "transaction": "Cumulus Media emerges from restructuring",
    "type": "restructuring",
    "note": "Cumulus restructured ~$1B in debt. Consolidated stations remain."
  }
];

// ------- Market Concentration (50 US markets) ----------
const marketConcentration = [
  {
    "id": 1,
    "name": "New York",
    "lat": 40.71,
    "lon": -74.01,
    "stations": 65,
    "c1990": 0.08,
    "c1996": 0.1,
    "c2002": 0.28,
    "c2010": 0.35,
    "c2024": 0.4
  },
  {
    "id": 2,
    "name": "Los Angeles",
    "lat": 34.05,
    "lon": -118.24,
    "stations": 62,
    "c1990": 0.09,
    "c1996": 0.11,
    "c2002": 0.3,
    "c2010": 0.36,
    "c2024": 0.42
  },
  {
    "id": 3,
    "name": "Chicago",
    "lat": 41.88,
    "lon": -87.63,
    "stations": 55,
    "c1990": 0.1,
    "c1996": 0.12,
    "c2002": 0.32,
    "c2010": 0.38,
    "c2024": 0.43
  },
  {
    "id": 4,
    "name": "Houston",
    "lat": 29.76,
    "lon": -95.37,
    "stations": 48,
    "c1990": 0.11,
    "c1996": 0.13,
    "c2002": 0.38,
    "c2010": 0.44,
    "c2024": 0.48
  },
  {
    "id": 5,
    "name": "Dallas-Fort Worth",
    "lat": 32.78,
    "lon": -96.8,
    "stations": 50,
    "c1990": 0.1,
    "c1996": 0.12,
    "c2002": 0.36,
    "c2010": 0.42,
    "c2024": 0.47
  },
  {
    "id": 6,
    "name": "Philadelphia",
    "lat": 39.95,
    "lon": -75.17,
    "stations": 45,
    "c1990": 0.12,
    "c1996": 0.14,
    "c2002": 0.35,
    "c2010": 0.4,
    "c2024": 0.45
  },
  {
    "id": 7,
    "name": "San Francisco",
    "lat": 37.77,
    "lon": -122.42,
    "stations": 42,
    "c1990": 0.11,
    "c1996": 0.13,
    "c2002": 0.34,
    "c2010": 0.39,
    "c2024": 0.44
  },
  {
    "id": 8,
    "name": "Washington DC",
    "lat": 38.91,
    "lon": -77.04,
    "stations": 45,
    "c1990": 0.1,
    "c1996": 0.12,
    "c2002": 0.32,
    "c2010": 0.38,
    "c2024": 0.43
  },
  {
    "id": 9,
    "name": "Boston",
    "lat": 42.36,
    "lon": -71.06,
    "stations": 40,
    "c1990": 0.12,
    "c1996": 0.14,
    "c2002": 0.36,
    "c2010": 0.41,
    "c2024": 0.46
  },
  {
    "id": 10,
    "name": "Atlanta",
    "lat": 33.75,
    "lon": -84.39,
    "stations": 42,
    "c1990": 0.11,
    "c1996": 0.14,
    "c2002": 0.38,
    "c2010": 0.43,
    "c2024": 0.48
  },
  {
    "id": 11,
    "name": "Miami",
    "lat": 25.76,
    "lon": -80.19,
    "stations": 38,
    "c1990": 0.13,
    "c1996": 0.15,
    "c2002": 0.37,
    "c2010": 0.42,
    "c2024": 0.46
  },
  {
    "id": 12,
    "name": "Phoenix",
    "lat": 33.45,
    "lon": -112.07,
    "stations": 35,
    "c1990": 0.14,
    "c1996": 0.16,
    "c2002": 0.4,
    "c2010": 0.46,
    "c2024": 0.5
  },
  {
    "id": 13,
    "name": "Seattle",
    "lat": 47.61,
    "lon": -122.33,
    "stations": 36,
    "c1990": 0.13,
    "c1996": 0.15,
    "c2002": 0.38,
    "c2010": 0.43,
    "c2024": 0.47
  },
  {
    "id": 14,
    "name": "Minneapolis",
    "lat": 44.98,
    "lon": -93.27,
    "stations": 35,
    "c1990": 0.14,
    "c1996": 0.16,
    "c2002": 0.42,
    "c2010": 0.47,
    "c2024": 0.51
  },
  {
    "id": 15,
    "name": "Denver",
    "lat": 39.74,
    "lon": -104.99,
    "stations": 34,
    "c1990": 0.13,
    "c1996": 0.16,
    "c2002": 0.41,
    "c2010": 0.46,
    "c2024": 0.5
  },
  {
    "id": 16,
    "name": "Detroit",
    "lat": 42.33,
    "lon": -83.05,
    "stations": 38,
    "c1990": 0.12,
    "c1996": 0.15,
    "c2002": 0.39,
    "c2010": 0.44,
    "c2024": 0.48
  },
  {
    "id": 17,
    "name": "Tampa",
    "lat": 27.95,
    "lon": -82.46,
    "stations": 32,
    "c1990": 0.15,
    "c1996": 0.17,
    "c2002": 0.43,
    "c2010": 0.48,
    "c2024": 0.52
  },
  {
    "id": 18,
    "name": "San Diego",
    "lat": 32.72,
    "lon": -117.16,
    "stations": 28,
    "c1990": 0.16,
    "c1996": 0.18,
    "c2002": 0.44,
    "c2010": 0.49,
    "c2024": 0.53
  },
  {
    "id": 19,
    "name": "Portland",
    "lat": 45.52,
    "lon": -122.68,
    "stations": 30,
    "c1990": 0.14,
    "c1996": 0.17,
    "c2002": 0.42,
    "c2010": 0.47,
    "c2024": 0.51
  },
  {
    "id": 20,
    "name": "Charlotte",
    "lat": 35.23,
    "lon": -80.84,
    "stations": 28,
    "c1990": 0.16,
    "c1996": 0.19,
    "c2002": 0.46,
    "c2010": 0.51,
    "c2024": 0.55
  },
  {
    "id": 21,
    "name": "Sacramento",
    "lat": 38.58,
    "lon": -121.49,
    "stations": 28,
    "c1990": 0.15,
    "c1996": 0.18,
    "c2002": 0.44,
    "c2010": 0.49,
    "c2024": 0.53
  },
  {
    "id": 22,
    "name": "Pittsburgh",
    "lat": 40.44,
    "lon": -80.0,
    "stations": 30,
    "c1990": 0.15,
    "c1996": 0.18,
    "c2002": 0.45,
    "c2010": 0.5,
    "c2024": 0.54
  },
  {
    "id": 23,
    "name": "Nashville",
    "lat": 36.16,
    "lon": -86.78,
    "stations": 26,
    "c1990": 0.17,
    "c1996": 0.2,
    "c2002": 0.48,
    "c2010": 0.53,
    "c2024": 0.56
  },
  {
    "id": 24,
    "name": "Indianapolis",
    "lat": 39.77,
    "lon": -86.16,
    "stations": 26,
    "c1990": 0.16,
    "c1996": 0.19,
    "c2002": 0.47,
    "c2010": 0.52,
    "c2024": 0.55
  },
  {
    "id": 25,
    "name": "Kansas City",
    "lat": 39.1,
    "lon": -94.58,
    "stations": 25,
    "c1990": 0.17,
    "c1996": 0.2,
    "c2002": 0.49,
    "c2010": 0.53,
    "c2024": 0.57
  },
  {
    "id": 26,
    "name": "Las Vegas",
    "lat": 36.17,
    "lon": -115.14,
    "stations": 24,
    "c1990": 0.18,
    "c1996": 0.21,
    "c2002": 0.5,
    "c2010": 0.54,
    "c2024": 0.58
  },
  {
    "id": 27,
    "name": "Cleveland",
    "lat": 41.5,
    "lon": -81.69,
    "stations": 28,
    "c1990": 0.16,
    "c1996": 0.19,
    "c2002": 0.48,
    "c2010": 0.52,
    "c2024": 0.56
  },
  {
    "id": 28,
    "name": "Columbus",
    "lat": 39.96,
    "lon": -83.0,
    "stations": 25,
    "c1990": 0.17,
    "c1996": 0.2,
    "c2002": 0.49,
    "c2010": 0.53,
    "c2024": 0.57
  },
  {
    "id": 29,
    "name": "San Antonio",
    "lat": 29.42,
    "lon": -98.49,
    "stations": 24,
    "c1990": 0.18,
    "c1996": 0.21,
    "c2002": 0.51,
    "c2010": 0.55,
    "c2024": 0.58
  },
  {
    "id": 30,
    "name": "Orlando",
    "lat": 28.54,
    "lon": -81.38,
    "stations": 26,
    "c1990": 0.17,
    "c1996": 0.2,
    "c2002": 0.48,
    "c2010": 0.53,
    "c2024": 0.56
  },
  {
    "id": 31,
    "name": "Milwaukee",
    "lat": 43.04,
    "lon": -87.91,
    "stations": 24,
    "c1990": 0.18,
    "c1996": 0.21,
    "c2002": 0.5,
    "c2010": 0.54,
    "c2024": 0.58
  },
  {
    "id": 32,
    "name": "Cincinnati",
    "lat": 39.1,
    "lon": -84.51,
    "stations": 25,
    "c1990": 0.17,
    "c1996": 0.2,
    "c2002": 0.49,
    "c2010": 0.54,
    "c2024": 0.57
  },
  {
    "id": 33,
    "name": "Salt Lake City",
    "lat": 40.76,
    "lon": -111.89,
    "stations": 22,
    "c1990": 0.19,
    "c1996": 0.22,
    "c2002": 0.52,
    "c2010": 0.56,
    "c2024": 0.6
  },
  {
    "id": 34,
    "name": "Raleigh-Durham",
    "lat": 35.78,
    "lon": -78.64,
    "stations": 24,
    "c1990": 0.18,
    "c1996": 0.21,
    "c2002": 0.5,
    "c2010": 0.54,
    "c2024": 0.58
  },
  {
    "id": 35,
    "name": "Memphis",
    "lat": 35.15,
    "lon": -90.05,
    "stations": 22,
    "c1990": 0.19,
    "c1996": 0.23,
    "c2002": 0.53,
    "c2010": 0.57,
    "c2024": 0.61
  },
  {
    "id": 36,
    "name": "Richmond",
    "lat": 37.54,
    "lon": -77.44,
    "stations": 22,
    "c1990": 0.19,
    "c1996": 0.22,
    "c2002": 0.52,
    "c2010": 0.56,
    "c2024": 0.6
  },
  {
    "id": 37,
    "name": "Louisville",
    "lat": 38.25,
    "lon": -85.76,
    "stations": 21,
    "c1990": 0.2,
    "c1996": 0.23,
    "c2002": 0.54,
    "c2010": 0.58,
    "c2024": 0.61
  },
  {
    "id": 38,
    "name": "New Orleans",
    "lat": 29.95,
    "lon": -90.07,
    "stations": 22,
    "c1990": 0.19,
    "c1996": 0.23,
    "c2002": 0.53,
    "c2010": 0.57,
    "c2024": 0.6
  },
  {
    "id": 39,
    "name": "Buffalo",
    "lat": 42.89,
    "lon": -78.88,
    "stations": 20,
    "c1990": 0.2,
    "c1996": 0.24,
    "c2002": 0.55,
    "c2010": 0.59,
    "c2024": 0.62
  },
  {
    "id": 40,
    "name": "Oklahoma City",
    "lat": 35.47,
    "lon": -97.52,
    "stations": 21,
    "c1990": 0.2,
    "c1996": 0.24,
    "c2002": 0.55,
    "c2010": 0.59,
    "c2024": 0.62
  },
  {
    "id": 41,
    "name": "Tucson",
    "lat": 32.22,
    "lon": -110.93,
    "stations": 18,
    "c1990": 0.22,
    "c1996": 0.26,
    "c2002": 0.58,
    "c2010": 0.62,
    "c2024": 0.65
  },
  {
    "id": 42,
    "name": "Birmingham",
    "lat": 33.52,
    "lon": -86.8,
    "stations": 20,
    "c1990": 0.21,
    "c1996": 0.25,
    "c2002": 0.56,
    "c2010": 0.6,
    "c2024": 0.63
  },
  {
    "id": 43,
    "name": "Albuquerque",
    "lat": 35.08,
    "lon": -106.65,
    "stations": 18,
    "c1990": 0.22,
    "c1996": 0.26,
    "c2002": 0.58,
    "c2010": 0.62,
    "c2024": 0.65
  },
  {
    "id": 44,
    "name": "Tulsa",
    "lat": 36.15,
    "lon": -95.99,
    "stations": 18,
    "c1990": 0.22,
    "c1996": 0.26,
    "c2002": 0.57,
    "c2010": 0.61,
    "c2024": 0.64
  },
  {
    "id": 45,
    "name": "Knoxville",
    "lat": 35.96,
    "lon": -83.92,
    "stations": 17,
    "c1990": 0.23,
    "c1996": 0.27,
    "c2002": 0.59,
    "c2010": 0.63,
    "c2024": 0.66
  },
  {
    "id": 46,
    "name": "Omaha",
    "lat": 41.26,
    "lon": -95.94,
    "stations": 18,
    "c1990": 0.22,
    "c1996": 0.26,
    "c2002": 0.58,
    "c2010": 0.62,
    "c2024": 0.65
  },
  {
    "id": 47,
    "name": "Boise",
    "lat": 43.62,
    "lon": -116.21,
    "stations": 15,
    "c1990": 0.24,
    "c1996": 0.28,
    "c2002": 0.61,
    "c2010": 0.65,
    "c2024": 0.68
  },
  {
    "id": 48,
    "name": "Spokane",
    "lat": 47.66,
    "lon": -117.43,
    "stations": 15,
    "c1990": 0.24,
    "c1996": 0.28,
    "c2002": 0.62,
    "c2010": 0.66,
    "c2024": 0.69
  },
  {
    "id": 49,
    "name": "Wichita",
    "lat": 37.69,
    "lon": -97.34,
    "stations": 14,
    "c1990": 0.25,
    "c1996": 0.29,
    "c2002": 0.63,
    "c2010": 0.67,
    "c2024": 0.7
  },
  {
    "id": 50,
    "name": "El Paso",
    "lat": 31.76,
    "lon": -106.49,
    "stations": 16,
    "c1990": 0.23,
    "c1996": 0.27,
    "c2002": 0.6,
    "c2010": 0.64,
    "c2024": 0.67
  }
];

// ------- Regulatory Timeline ----------
const regulatoryTimeline = [
  {
    "year": 1927,
    "label": "Radio Act of 1927",
    "desc": "Established the Federal Radio Commission. First codification of the 'public interest, convenience, and necessity' standard for broadcast licensing. Created the legal foundation that airwaves are a public resource.",
    "type": "regulation"
  },
  {
    "year": 1934,
    "label": "Communications Act of 1934",
    "desc": "Created the FCC, replacing the Federal Radio Commission. Established that airwaves are a public resource, licensed in the 'public interest, convenience, and necessity.' Set ownership caps: 7 AM, 7 FM, 7 TV stations per entity.",
    "type": "regulation"
  },
  {
    "year": 1941,
    "label": "Chain Broadcasting Rules",
    "desc": "FCC rules limiting network control over affiliate stations. Required that affiliates retain the right to reject network programming. Broke NBC into two networks (NBC and ABC).",
    "type": "regulation"
  },
  {
    "year": 1949,
    "label": "Fairness Doctrine",
    "desc": "Required broadcasters to present contrasting viewpoints on controversial issues of public importance. Codified the public trustee model of broadcasting. Broadcasters had an affirmative obligation to cover issues and provide balance.",
    "type": "regulation"
  },
  {
    "year": 1960,
    "label": "Programming Guidelines",
    "desc": "FCC issued guidelines requiring stations to serve community needs through local programming, news, and public affairs content. Listed 14 categories of programming that serve the public interest.",
    "type": "regulation"
  },
  {
    "year": 1967,
    "label": "Public Broadcasting Act",
    "desc": "Created the Corporation for Public Broadcasting (CPB), leading to PBS and NPR. Established the principle that some broadcasting should be insulated from commercial pressures entirely.",
    "type": "regulation"
  },
  {
    "year": 1970,
    "label": "Financial Interest and Syndication Rules",
    "desc": "Prevented TV networks from owning the programs they broadcast, promoting diversity of content producers. Later repealed in 1995.",
    "type": "regulation"
  },
  {
    "year": 1971,
    "label": "Ascertainment Requirements",
    "desc": "Stations required to survey community leaders and the public to identify local issues, then demonstrate in license renewal applications how their programming addressed those issues.",
    "type": "regulation"
  },
  {
    "year": 1975,
    "label": "Cross-Ownership Ban",
    "desc": "Prohibited common ownership of a newspaper and broadcast station in the same market. Designed to preserve media voice diversity in local markets.",
    "type": "regulation"
  },
  {
    "year": 1981,
    "label": "Deregulation of Radio",
    "desc": "FCC under Mark Fowler eliminated formal ascertainment requirements, programming guidelines, and commercial time limits for radio. Fowler described television as 'a toaster with pictures.'",
    "type": "deregulation"
  },
  {
    "year": 1984,
    "label": "Deregulation of Television / Ownership Cap Raised",
    "desc": "FCC extended radio deregulation to television: eliminated programming guidelines and ascertainment requirements. Raised ownership cap from 7-7-7 to 12-12-12 (12 AM, 12 FM, 12 TV stations per entity).",
    "type": "deregulation"
  },
  {
    "year": 1987,
    "label": "Fairness Doctrine Repealed",
    "desc": "FCC eliminated the Fairness Doctrine, arguing it chilled free speech and was no longer necessary given the growth of media outlets. Congress passed legislation to codify the doctrine; President Reagan vetoed it. Removed the obligation to present balanced viewpoints. Opened the door to partisan talk radio.",
    "type": "deregulation"
  },
  {
    "year": 1992,
    "label": "Ownership Caps Raised",
    "desc": "FCC raised national ownership caps from 12-12 to 18-18, then to 20-20 (later raised to 30-30 before the 1996 Act). Each step enabled larger station groups.",
    "type": "deregulation"
  },
  {
    "year": 1996,
    "label": "Telecommunications Act of 1996",
    "desc": "Eliminated the national radio ownership cap entirely. Raised TV ownership cap to 35% national audience reach. Raised local radio ownership limits based on market size (up to 8 stations in large markets). Triggered the largest wave of media consolidation in American history. Within four years, Clear Channel grew from 40 stations to 1,200. The number of radio station owners fell from 5,100 to ~3,400 in five years.",
    "type": "deregulation"
  },
  {
    "year": 2003,
    "label": "FCC Loosens Cross-Ownership Rules",
    "desc": "FCC voted 3-2 to relax newspaper/broadcast cross-ownership rules and raise TV ownership cap from 35% to 45%. Generated 3 million public comments, the most in FCC history at that time. Third Circuit Court of Appeals blocked most of the changes in Prometheus Radio Project v. FCC (2004).",
    "type": "deregulation"
  },
  {
    "year": 2004,
    "label": "Prometheus Radio Project v. FCC",
    "desc": "Third Circuit Court of Appeals blocked FCC's 2003 ownership deregulation. Found FCC had not adequately justified relaxing cross-ownership rules. Remanded for further proceedings that continued for nearly two decades.",
    "type": "judicial"
  },
  {
    "year": 2007,
    "label": "FCC Again Loosens Cross-Ownership",
    "desc": "FCC voted to allow newspaper/broadcast cross-ownership in top-20 markets under certain conditions. Again challenged in court.",
    "type": "deregulation"
  },
  {
    "year": 2017,
    "label": "Cross-Ownership Rules Repealed",
    "desc": "FCC under Chairman Ajit Pai eliminated the newspaper/broadcast cross-ownership ban and the radio/TV cross-ownership rule, both in place since the 1970s. Ended the UHF discount restoration that effectively raised TV ownership cap above 39%.",
    "type": "deregulation"
  },
  {
    "year": 2017,
    "label": "Main Studio Rule Eliminated",
    "desc": "FCC eliminated the requirement that stations maintain a main studio in or near their community of license. Stations could now be operated entirely from remote locations, ending the requirement of physical local presence.",
    "type": "deregulation"
  },
  {
    "year": 2021,
    "label": "Supreme Court Upholds FCC Deregulation",
    "desc": "In FCC v. Prometheus Radio Project, the Supreme Court unanimously upheld FCC's 2017 repeal of cross-ownership rules. Ended nearly two decades of litigation. Justice Kavanaugh wrote that the FCC had reasonably concluded the old rules were no longer necessary.",
    "type": "judicial"
  },
  {
    "year": 2024,
    "label": "Reform Efforts Stalled",
    "desc": "Congressional attempts to restore local ownership incentives, reinstate public interest obligations, and address media consolidation stalled in committee. The Local Journalism Sustainability Act and similar proposals failed to advance. Status quo consolidation continues.",
    "type": "stalled"
  }
];

// ------- Sinclair Footprint ----------
const sinclairFootprint = {
  "description": "Sinclair Broadcast Group station footprint and must-run segment data",
  "methodology": "Station list compiled from Sinclair SEC filings, FCC license database, and station websites. Must-run segment data from published journalism and media criticism. This is a representative sample of ~30 notable stations; Sinclair operates approximately 185 stations total.",
  "sources": [
    "Sinclair Broadcast Group SEC filings (10-K)",
    "FCC license database",
    "Deadspin / Timothy Burke (2018 synchronized script compilation)",
    "Columbia Journalism Review Sinclair coverage (2017-2024)"
  ],
  "summary": {
    "total_stations": 185,
    "total_markets": 86,
    "household_reach_pct": 40,
    "headquarters": "Hunt Valley, Maryland",
    "founded": 1971,
    "public_since": 1995,
    "ceo": "Chris Ripley",
    "founder": "Julian Sinclair Smith",
    "stations_1996": 31,
    "stations_2002": 62,
    "stations_2010": 77,
    "stations_2017": 173,
    "stations_2024": 185,
    "tribune_deal_blocked": true,
    "tribune_deal_year": 2018,
    "tribune_deal_would_have_reached_pct": 72
  },
  "stations": [
    {
      "call_sign": "WJLA-TV",
      "market": "Washington DC",
      "state": "DC",
      "network": "ABC",
      "acquired": 2014,
      "lat": 38.91,
      "lon": -77.04,
      "note": "Acquired from Allbritton. $985M deal."
    },
    {
      "call_sign": "WJZ-TV",
      "market": "Baltimore",
      "state": "MD",
      "network": "CBS",
      "acquired": 2017,
      "lat": 39.29,
      "lon": -76.61,
      "note": "Sinclair headquarters market"
    },
    {
      "call_sign": "KOMO-TV",
      "market": "Seattle",
      "state": "WA",
      "network": "ABC",
      "acquired": 2013,
      "lat": 47.61,
      "lon": -122.33,
      "note": "Acquired from Fisher Communications"
    },
    {
      "call_sign": "KATU-TV",
      "market": "Portland",
      "state": "OR",
      "network": "ABC",
      "acquired": 2013,
      "lat": 45.52,
      "lon": -122.68,
      "note": "Acquired from Fisher Communications"
    },
    {
      "call_sign": "WBFF-TV",
      "market": "Baltimore",
      "state": "MD",
      "network": "FOX",
      "acquired": 1991,
      "lat": 39.29,
      "lon": -76.61,
      "note": "Original Sinclair flagship station"
    },
    {
      "call_sign": "WPGH-TV",
      "market": "Pittsburgh",
      "state": "PA",
      "network": "FOX",
      "acquired": 2014,
      "lat": 40.44,
      "lon": -80.0,
      "note": null
    },
    {
      "call_sign": "WTTE-TV",
      "market": "Columbus",
      "state": "OH",
      "network": "FOX",
      "acquired": 1996,
      "lat": 39.96,
      "lon": -83.0,
      "note": "Acquired from Heritage Communications"
    },
    {
      "call_sign": "WSYX-TV",
      "market": "Columbus",
      "state": "OH",
      "network": "ABC",
      "acquired": 1996,
      "lat": 39.96,
      "lon": -83.0,
      "note": null
    },
    {
      "call_sign": "WDKY-TV",
      "market": "Lexington",
      "state": "KY",
      "network": "FOX",
      "acquired": 1997,
      "lat": 38.04,
      "lon": -84.5,
      "note": null
    },
    {
      "call_sign": "KABB-TV",
      "market": "San Antonio",
      "state": "TX",
      "network": "FOX",
      "acquired": 1998,
      "lat": 29.42,
      "lon": -98.49,
      "note": "Acquired from Sullivan Broadcasting"
    },
    {
      "call_sign": "WSTR-TV",
      "market": "Cincinnati",
      "state": "OH",
      "network": "MyNetwork",
      "acquired": 1998,
      "lat": 39.1,
      "lon": -84.51,
      "note": null
    },
    {
      "call_sign": "WTVZ-TV",
      "market": "Norfolk",
      "state": "VA",
      "network": "MyNetwork",
      "acquired": 2001,
      "lat": 36.85,
      "lon": -76.29,
      "note": null
    },
    {
      "call_sign": "WLFL-TV",
      "market": "Raleigh",
      "state": "NC",
      "network": "CW",
      "acquired": 2002,
      "lat": 35.78,
      "lon": -78.64,
      "note": null
    },
    {
      "call_sign": "KOCB-TV",
      "market": "Oklahoma City",
      "state": "OK",
      "network": "CW",
      "acquired": 1997,
      "lat": 35.47,
      "lon": -97.52,
      "note": null
    },
    {
      "call_sign": "WZTV-TV",
      "market": "Nashville",
      "state": "TN",
      "network": "FOX",
      "acquired": 2017,
      "lat": 36.16,
      "lon": -86.78,
      "note": null
    },
    {
      "call_sign": "WCHS-TV",
      "market": "Charleston WV",
      "state": "WV",
      "network": "ABC",
      "acquired": 1998,
      "lat": 38.35,
      "lon": -81.63,
      "note": null
    },
    {
      "call_sign": "WVAH-TV",
      "market": "Charleston WV",
      "state": "WV",
      "network": "FOX",
      "acquired": 1998,
      "lat": 38.35,
      "lon": -81.63,
      "note": null
    },
    {
      "call_sign": "WXLV-TV",
      "market": "Greensboro",
      "state": "NC",
      "network": "ABC",
      "acquired": 1997,
      "lat": 36.07,
      "lon": -79.79,
      "note": null
    },
    {
      "call_sign": "WTVH-TV",
      "market": "Syracuse",
      "state": "NY",
      "network": "CBS",
      "acquired": 2014,
      "lat": 43.05,
      "lon": -76.15,
      "note": null
    },
    {
      "call_sign": "WGME-TV",
      "market": "Portland ME",
      "state": "ME",
      "network": "CBS",
      "acquired": 2013,
      "lat": 43.66,
      "lon": -70.26,
      "note": null
    },
    {
      "call_sign": "KUTV-TV",
      "market": "Salt Lake City",
      "state": "UT",
      "network": "CBS",
      "acquired": 2017,
      "lat": 40.76,
      "lon": -111.89,
      "note": null
    },
    {
      "call_sign": "KATV-TV",
      "market": "Little Rock",
      "state": "AR",
      "network": "ABC",
      "acquired": 2014,
      "lat": 34.75,
      "lon": -92.29,
      "note": "Acquired from Allbritton"
    },
    {
      "call_sign": "WHTM-TV",
      "market": "Harrisburg",
      "state": "PA",
      "network": "ABC",
      "acquired": 2014,
      "lat": 40.27,
      "lon": -76.88,
      "note": "Acquired from Allbritton"
    },
    {
      "call_sign": "KDSM-TV",
      "market": "Des Moines",
      "state": "IA",
      "network": "FOX",
      "acquired": 2012,
      "lat": 41.59,
      "lon": -93.62,
      "note": null
    },
    {
      "call_sign": "WEAR-TV",
      "market": "Pensacola",
      "state": "FL",
      "network": "ABC",
      "acquired": 2012,
      "lat": 30.44,
      "lon": -87.22,
      "note": null
    },
    {
      "call_sign": "WKRC-TV",
      "market": "Cincinnati",
      "state": "OH",
      "network": "CBS",
      "acquired": 2017,
      "lat": 39.1,
      "lon": -84.51,
      "note": null
    },
    {
      "call_sign": "WDTN-TV",
      "market": "Dayton",
      "state": "OH",
      "network": "NBC",
      "acquired": 2017,
      "lat": 39.76,
      "lon": -84.19,
      "note": null
    },
    {
      "call_sign": "WWMT-TV",
      "market": "Kalamazoo",
      "state": "MI",
      "network": "CBS",
      "acquired": 2017,
      "lat": 42.29,
      "lon": -85.59,
      "note": null
    },
    {
      "call_sign": "WTVG-TV",
      "market": "Toledo",
      "state": "OH",
      "network": "ABC",
      "acquired": 2017,
      "lat": 41.65,
      "lon": -83.54,
      "note": null
    }
  ],
  "must_run_segments": [
    {
      "name": "Bottom Line with Boris Epshteyn",
      "type": "commentary",
      "duration_seconds": 90,
      "frequency": "daily",
      "years_active": "2017-present",
      "description": "Daily political commentary segment produced centrally at Sinclair headquarters in Hunt Valley, Maryland. Inserted into local newscasts at ~185 stations. Boris Epshteyn is a former Trump campaign advisor and brief White House aide.",
      "source": "CJR, Politico, published media criticism"
    },
    {
      "name": "Behind the Headlines with Mark Hyman",
      "type": "commentary",
      "duration_seconds": 60,
      "frequency": "weekly",
      "years_active": "2001-2017",
      "description": "Weekly conservative commentary segment aired during local newscasts. Mark Hyman was Sinclair's VP of corporate relations.",
      "source": "Published media criticism, FCC complaint records"
    },
    {
      "name": "Terrorism Alert Desk",
      "type": "news_segment",
      "duration_seconds": 120,
      "frequency": "daily",
      "years_active": "2017-2019",
      "description": "Daily segment on terrorism threats, produced centrally and inserted into local newscasts. Critics noted it prioritized fear over local relevance.",
      "source": "CJR, Deadspin"
    },
    {
      "name": "Full Measure with Sharyl Attkisson",
      "type": "investigative",
      "duration_seconds": 1800,
      "frequency": "weekly",
      "years_active": "2015-present",
      "description": "Weekly Sunday investigative news program produced by Sinclair. Airs on Sinclair stations nationally.",
      "source": "Sinclair Broadcast Group"
    },
    {
      "name": "Sinclair promotional script (2018)",
      "type": "promotional",
      "duration_seconds": 90,
      "frequency": "one-time",
      "years_active": "2018",
      "description": "In March 2018, anchors at dozens of Sinclair stations read identical scripts warning viewers about 'biased and false news.' Video compilation by Deadspin's Timothy Burke showed the synchronized delivery across markets. The incident drew widespread criticism and demonstrated centralized editorial control.",
      "source": "Deadspin (Timothy Burke), widespread news coverage"
    }
  ]
};

// ------- News Deserts ----------
const newsDeserts = {
  "summary": {
    "total_us_counties": 3143,
    "news_desert_counties": 204,
    "one_source_counties": 1766,
    "ghost_newspaper_counties": 228,
    "newspapers_closed_since_2005": 2900,
    "newspapers_remaining": 6000,
    "weeklies_closed_pct": 0.33,
    "dailies_closed_pct": 0.25,
    "sources": [
      "UNC Hussman School, 'News Deserts and Ghost Newspapers' (2024)",
      "Medill School, 'State of Local News' (2024)"
    ]
  },
  "newsroom_employment": [
    {
      "year": 1990,
      "newspaper_newsroom": 56100,
      "broadcast_newsroom": 28300,
      "total": 84400,
      "source": "ASNE/BLS estimates"
    },
    {
      "year": 1995,
      "newspaper_newsroom": 53800,
      "broadcast_newsroom": 27500,
      "total": 81300,
      "source": "ASNE census"
    },
    {
      "year": 2000,
      "newspaper_newsroom": 56400,
      "broadcast_newsroom": 28000,
      "total": 84400,
      "source": "ASNE census"
    },
    {
      "year": 2004,
      "newspaper_newsroom": 54200,
      "broadcast_newsroom": 27000,
      "total": 81200,
      "source": "ASNE census / BLS"
    },
    {
      "year": 2005,
      "newspaper_newsroom": 52600,
      "broadcast_newsroom": 26500,
      "total": 79100,
      "source": "ASNE census / BLS"
    },
    {
      "year": 2006,
      "newspaper_newsroom": 49900,
      "broadcast_newsroom": 26000,
      "total": 75900,
      "source": "ASNE census / BLS"
    },
    {
      "year": 2007,
      "newspaper_newsroom": 48600,
      "broadcast_newsroom": 25500,
      "total": 74100,
      "source": "ASNE census / BLS"
    },
    {
      "year": 2008,
      "newspaper_newsroom": 46700,
      "broadcast_newsroom": 25000,
      "total": 71700,
      "source": "BLS OEWS. Peak recent measurement."
    },
    {
      "year": 2009,
      "newspaper_newsroom": 41500,
      "broadcast_newsroom": 24000,
      "total": 65500,
      "source": "Great Recession layoffs. BLS OEWS."
    },
    {
      "year": 2010,
      "newspaper_newsroom": 38000,
      "broadcast_newsroom": 23500,
      "total": 61500,
      "source": "BLS OEWS"
    },
    {
      "year": 2011,
      "newspaper_newsroom": 36700,
      "broadcast_newsroom": 23000,
      "total": 59700,
      "source": "BLS OEWS"
    },
    {
      "year": 2012,
      "newspaper_newsroom": 35500,
      "broadcast_newsroom": 22500,
      "total": 58000,
      "source": "BLS OEWS"
    },
    {
      "year": 2013,
      "newspaper_newsroom": 34200,
      "broadcast_newsroom": 22000,
      "total": 56200,
      "source": "BLS OEWS"
    },
    {
      "year": 2014,
      "newspaper_newsroom": 32900,
      "broadcast_newsroom": 21500,
      "total": 54400,
      "source": "BLS OEWS / Pew"
    },
    {
      "year": 2015,
      "newspaper_newsroom": 31800,
      "broadcast_newsroom": 21000,
      "total": 52800,
      "source": "BLS OEWS / Pew"
    },
    {
      "year": 2016,
      "newspaper_newsroom": 30400,
      "broadcast_newsroom": 20500,
      "total": 50900,
      "source": "BLS OEWS / Pew"
    },
    {
      "year": 2017,
      "newspaper_newsroom": 28700,
      "broadcast_newsroom": 20000,
      "total": 48700,
      "source": "BLS OEWS / Pew"
    },
    {
      "year": 2018,
      "newspaper_newsroom": 27600,
      "broadcast_newsroom": 19500,
      "total": 47100,
      "source": "BLS OEWS / Pew"
    },
    {
      "year": 2019,
      "newspaper_newsroom": 24300,
      "broadcast_newsroom": 18800,
      "total": 43100,
      "source": "BLS OEWS / Pew"
    },
    {
      "year": 2020,
      "newspaper_newsroom": 22900,
      "broadcast_newsroom": 17500,
      "total": 40400,
      "source": "COVID layoffs. BLS OEWS."
    },
    {
      "year": 2021,
      "newspaper_newsroom": 21400,
      "broadcast_newsroom": 17000,
      "total": 38400,
      "source": "BLS OEWS / Pew"
    },
    {
      "year": 2022,
      "newspaper_newsroom": 20200,
      "broadcast_newsroom": 16500,
      "total": 36700,
      "source": "BLS OEWS / Medill"
    },
    {
      "year": 2023,
      "newspaper_newsroom": 18500,
      "broadcast_newsroom": 16000,
      "total": 34500,
      "source": "BLS OEWS / Medill State of Local News"
    },
    {
      "year": 2024,
      "newspaper_newsroom": 17200,
      "broadcast_newsroom": 15500,
      "total": 32700,
      "source": "BLS OEWS estimate / Medill"
    }
  ],
  "state_news_deserts": [
    {
      "state": "TX",
      "name": "Texas",
      "news_desert_counties": 28,
      "total_counties": 254,
      "pct": 0.11
    },
    {
      "state": "GA",
      "name": "Georgia",
      "news_desert_counties": 17,
      "total_counties": 159,
      "pct": 0.107
    },
    {
      "state": "KY",
      "name": "Kentucky",
      "news_desert_counties": 14,
      "total_counties": 120,
      "pct": 0.117
    },
    {
      "state": "KS",
      "name": "Kansas",
      "news_desert_counties": 13,
      "total_counties": 105,
      "pct": 0.124
    },
    {
      "state": "MT",
      "name": "Montana",
      "news_desert_counties": 10,
      "total_counties": 56,
      "pct": 0.179
    },
    {
      "state": "NE",
      "name": "Nebraska",
      "news_desert_counties": 10,
      "total_counties": 93,
      "pct": 0.108
    },
    {
      "state": "MS",
      "name": "Mississippi",
      "news_desert_counties": 9,
      "total_counties": 82,
      "pct": 0.11
    },
    {
      "state": "SD",
      "name": "South Dakota",
      "news_desert_counties": 8,
      "total_counties": 66,
      "pct": 0.121
    },
    {
      "state": "ND",
      "name": "North Dakota",
      "news_desert_counties": 7,
      "total_counties": 53,
      "pct": 0.132
    },
    {
      "state": "AL",
      "name": "Alabama",
      "news_desert_counties": 7,
      "total_counties": 67,
      "pct": 0.104
    },
    {
      "state": "VA",
      "name": "Virginia",
      "news_desert_counties": 6,
      "total_counties": 133,
      "pct": 0.045
    },
    {
      "state": "MO",
      "name": "Missouri",
      "news_desert_counties": 6,
      "total_counties": 115,
      "pct": 0.052
    },
    {
      "state": "NC",
      "name": "North Carolina",
      "news_desert_counties": 5,
      "total_counties": 100,
      "pct": 0.05
    },
    {
      "state": "TN",
      "name": "Tennessee",
      "news_desert_counties": 5,
      "total_counties": 95,
      "pct": 0.053
    },
    {
      "state": "OK",
      "name": "Oklahoma",
      "news_desert_counties": 5,
      "total_counties": 77,
      "pct": 0.065
    },
    {
      "state": "CO",
      "name": "Colorado",
      "news_desert_counties": 5,
      "total_counties": 64,
      "pct": 0.078
    },
    {
      "state": "AR",
      "name": "Arkansas",
      "news_desert_counties": 4,
      "total_counties": 75,
      "pct": 0.053
    },
    {
      "state": "OH",
      "name": "Ohio",
      "news_desert_counties": 4,
      "total_counties": 88,
      "pct": 0.045
    },
    {
      "state": "PA",
      "name": "Pennsylvania",
      "news_desert_counties": 4,
      "total_counties": 67,
      "pct": 0.06
    },
    {
      "state": "WV",
      "name": "West Virginia",
      "news_desert_counties": 4,
      "total_counties": 55,
      "pct": 0.073
    }
  ],
  "democratic_impact": {
    "description": "Published research on democratic effects of news deserts",
    "findings": [
      {
        "finding": "Lower voter turnout in news deserts",
        "magnitude": "3-5 percentage points lower in counties without local news",
        "source": "Darr, Hitt, & Dunaway, 'Newspaper Closures Polarize Voting Behavior' (Journal of Communication, 2018)",
        "confidence": "HIGH"
      },
      {
        "finding": "Higher municipal borrowing costs",
        "magnitude": "5-11 basis points higher in counties that lost newspapers",
        "source": "Gao, Lee, & Murphy, 'Financing Dies in Darkness' (Journal of Financial Economics, 2020)",
        "confidence": "HIGH"
      },
      {
        "finding": "Less competitive local elections",
        "magnitude": "Incumbents win at higher rates in news desert counties",
        "source": "Rubado & Jennings, 'Political Consequences of News Desert' (Journal of Politics, 2020)",
        "confidence": "HIGH"
      },
      {
        "finding": "Higher rates of government corruption",
        "magnitude": "Corruption convictions increase when newspapers close",
        "source": "Gao, Lee, & Murphy (2020); Snyder & Stromberg (2010)",
        "confidence": "CANDIDATE"
      },
      {
        "finding": "Reduced civic engagement",
        "magnitude": "Fewer people attend town halls or contact local officials",
        "source": "Shaker, 'Dead Newspapers and Citizens' Civic Engagement' (Political Communication, 2014)",
        "confidence": "HIGH"
      }
    ]
  }
};

// ------- Pipeline metadata ----------
const META = {
  "pipeline_version": "1.0.0",
  "data_sources": {
    "ownership": [
      "FCC Annual Reports",
      "BIA/Kelsey via Free Press 'Off the Dial' (2007)",
      "Future of Music Coalition 'Radio Deregulation' (2006)",
      "Eli Noam, 'Media Ownership and Concentration in America' (2009)"
    ],
    "markets": [
      "BIA/Kelsey Investing in Radio Market Reports",
      "FCC Media Ownership Studies (2002, 2006, 2010)",
      "Free Press, 'Off the Dial' (2007)",
      "Prometheus Radio Project v. FCC record (2004)"
    ],
    "transfers": [
      "FCC CDBS license transfer records",
      "SEC EDGAR filings (Clear Channel, iHeartMedia, Cumulus, Sinclair, Nexstar)",
      "Broadcasting & Cable trade publication",
      "Radio Ink industry reports"
    ],
    "news_deserts": [
      "UNC Hussman School, 'News Deserts and Ghost Newspapers' (2018-2024)",
      "Medill School, 'State of Local News' (2022-2024)",
      "Bureau of Labor Statistics OEWS (NAICS 5111, 5151)",
      "Pew Research Center 'State of the News Media' (2004-2024)"
    ],
    "sinclair": [
      "Sinclair Broadcast Group SEC filings (10-K)",
      "FCC license database",
      "Deadspin / Timothy Burke (2018 synchronized script compilation)",
      "Columbia Journalism Review Sinclair coverage (2017-2024)"
    ],
    "regulatory": [
      "FCC archived orders and rulings",
      "Federal Register (47 C.F.R.)",
      "Congressional legislation (public laws)",
      "Federal court decisions",
      "Krattenmaker & Powe, 'Regulating Broadcast Programming' (1994)",
      "McChesney, 'The Problem of the Media' (2004)"
    ]
  },
  "methodology": {
    "consolidation": "HHI computed from published ownership distribution data. National HHI reflects the sum of squared market shares of all owners. Pre-1996 values are low due to strict ownership caps (max 40 stations). Post-1996 values rise as Clear Channel/iHeartMedia captured ~11% of all stations. Market-level HHIs (see market_concentration.json) are significantly higher.",
    "markets": "Concentration score is normalized HHI (0=perfectly competitive, 1=monopoly). Based on published BIA/Kelsey revenue share data and FCC Media Ownership Studies. Pattern: large markets consolidated slower due to more stations; small markets reached high concentration by 2002. All markets show significant increases post-1996.",
    "transfers": "Transactions compiled from SEC filings, FCC license transfer records, and trade press reports. Prices from SEC filings and published reports. Focus on the consolidation wave triggered by the 1996 Telecommunications Act.",
    "news_deserts": "County-level news desert classifications from UNC Hussman School research. Newsroom employment from BLS Occupational Employment and Wage Statistics. Democratic impact findings from published peer-reviewed research.",
    "regulatory": "Timeline compiled from FCC archived orders, Federal Register entries, congressional legislation, and federal court decisions. Citations provided for each entry. This is the factual record of how the public interest obligation was established and systematically dismantled."
  },
  "confidence": {
    "ownership_counts": "HIGH - FCC records and published research",
    "hhi_national": "HIGH - computed from published ownership distributions",
    "market_concentration": "HIGH - BIA/Kelsey and FCC studies",
    "transfers": "HIGH - SEC filings and FCC records",
    "news_deserts": "HIGH - UNC Hussman School research",
    "sinclair_footprint": "HIGH - SEC filings and FCC database",
    "regulatory_timeline": "HIGH - statutory and regulatory record"
  }
};

// ------- Note for Year ----------
function noteForYear(year) {
  const notes = {
  "1934": "Communications Act signed. ~600 AM stations.",
  "1940": "765 commercial AM stations licensed",
  "1942": "Wartime freeze on new licenses",
  "1945": "Post-war boom begins. FM authorized.",
  "1949": "Fairness Doctrine adopted",
  "1950": "TV licensing begins in earnest",
  "1960": "FCC programming guidelines issued",
  "1967": "Public Broadcasting Act",
  "1971": "Ascertainment requirements",
  "1975": "Cross-ownership rules adopted",
  "1980": "Deregulation begins under Carter FCC",
  "1984": "FCC raises ownership cap to 12-12-12",
  "1987": "Fairness Doctrine repealed",
  "1992": "FCC raises cap to 18-18, then 20-20",
  "1996": "Telecom Act signed Feb 8. Peak ownership diversity.",
  "1997": "First wave of acquisitions. ~400 owners eliminated.",
  "1998": "Chancellor/Capstar merger. Clear Channel accelerates.",
  "1999": "Clear Channel merges with AMFM. 830 stations.",
  "2000": "Clear Channel peaks at ~1,200 stations.",
  "2001": "Ownership count collapses. HHI spikes.",
  "2003": "FCC loosens cross-ownership; courts block it",
  "2008": "Clear Channel taken private. $19.4B debt.",
  "2009": "Recession accelerates distress sales",
  "2014": "iHeartMedia reports $20B long-term debt",
  "2017": "Cross-ownership and main studio rules repealed",
  "2018": "iHeartMedia bankruptcy. Largest radio bankruptcy ever.",
  "2020": "COVID disrupts local broadcasting",
  "2024": "Reform efforts stalled. ~2,800 owners for 11,500+ stations.",
  "1927": "Radio Act of 1927: Established the Federal Radio Commission. First codification of the 'public interest, convenience, a",
  "1941": "Chain Broadcasting Rules: FCC rules limiting network control over affiliate stations. Required that affiliates retain the righ",
  "1970": "Financial Interest and Syndication Rules: Prevented TV networks from owning the programs they broadcast, promoting diversity of content produc",
  "1981": "Deregulation of Radio: FCC under Mark Fowler eliminated formal ascertainment requirements, programming guidelines, and comm",
  "2004": "Prometheus Radio Project v. FCC: Third Circuit Court of Appeals blocked FCC's 2003 ownership deregulation. Found FCC had not adequate",
  "2007": "FCC Again Loosens Cross-Ownership: FCC voted to allow newspaper/broadcast cross-ownership in top-20 markets under certain conditions. A",
  "2021": "Supreme Court Upholds FCC Deregulation: In FCC v. Prometheus Radio Project, the Supreme Court unanimously upheld FCC's 2017 repeal of cross-"
};
  if (notes[year]) return notes[year];
  if (year >= 1996 && year <= 2002) return 'Peak consolidation era. Thousands of stations change hands.';
  return null;
}

// ------- Expose to window ----------
Object.assign(window, {
  consolidationColor, lerpColor,
  formatPrice, formatNumber,
  ownershipTimeline, SPECTRUM_STATS,
  transferLog, marketConcentration,
  regulatoryTimeline, noteForYear,
  sinclairFootprint, newsDeserts, META,
});
